#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi
TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()
_clear() { [[ -t 1 ]] || return 0; if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi; }
banner() { _clear; printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"; printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"; printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"; printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'; printf '  later, since it remembers values already saved.%s\n' "$RESET"; pause "Ready to start?"; }
stage() { _clear; _STAGE_INDEX=$((_STAGE_INDEX + 1)); printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"; }
say() { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
open_url() { local url="$1"; printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"; { if command -v wslview >/dev/null 2>&1; then wslview "$url"; elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"; elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"; elif command -v open >/dev/null 2>&1; then open "$url"; else warn "couldn't open a browser; visit it manually: $url"; fi; } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"; }
pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }
confirm() { local reply=""; printf '  %s? %s [y/N] ' "$YELLOW" "$1"; read -r reply || true; [[ "$reply" =~ ^[Yy] ]]; }
_existing() { [[ -f "$ENV_FILE" ]] || return 1; local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1; printf '%s' "${line#*=}"; }
ask() { local key="$1" prompt="$2" current input; current=$(_existing "$key" || true); if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi; read -r input || true; [[ -z "$input" && -n "$current" ]] && input="$current"; printf -v "$key" '%s' "$input"; }
ask_secret() { local key="$1" prompt="$2" current input; current=$(_existing "$key" || true); if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi; read -rs input || true; printf '\n'; [[ -z "$input" && -n "$current" ]] && input="$current"; printf -v "$key" '%s' "$input"; }
write_env() { local key="$1" value="$2" tmp; touch "$ENV_FILE"; tmp=$(mktemp); grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true; printf '%s=%s\n' "$key" "$value" >> "$tmp"; mv "$tmp" "$ENV_FILE"; WRITTEN_ENV+=("$key"); printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"; }
set_secret() { local name="$1" value="$2"; if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then WRITTEN_SECRET+=("$name"); printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"; return; fi; fi; SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)"); warn "skipped GitHub secret $name: gh not ready; set it later"; }
set_var() { local name="$1" value="$2"; if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then if gh variable set "$name" --body "$value" >/dev/null 2>&1; then printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"; return; fi; fi; SKIPPED+=("GitHub variable $name"); warn "skipped GitHub variable $name, gh not ready; set it later"; }
finish() { _clear; printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"; (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"; (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"; if (( ${#SKIPPED[@]} )); then printf '\n'; warn "still to do by hand:"; for s in "${SKIPPED[@]}"; do note "  - $s"; done; fi; printf '\n'; }

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
banner "Find Me Home production setup"

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI authentication is required so CI configuration cannot be skipped"
  exit 1
fi

# This production wizard must fail closed even though the shared wizard library
# permits optional GitHub setup.
set_secret() {
  local name="$1" value="$2"
  printf '%s' "$value" | gh secret set "$name"
  WRITTEN_SECRET+=("$name")
  printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
}
set_var() {
  local name="$1" value="$2"
  gh variable set "$name" --body "$value"
  printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
}

stage "Cloudflare access"
say "Create a token limited to this account with Workers Scripts: Edit and Account Settings: Read."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Select Create Token, use a custom token, add the two permissions, and restrict Account Resources to this account."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Copy the Account ID from the Workers & Pages overview."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

stage "Workers subdomain"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "If prompted, choose and confirm the account workers.dev subdomain. Otherwise confirm the existing subdomain is active."
pause "Press Enter when workers.dev is active."

stage "Deploy production Worker"
say "This deploys find-me-home-operations with CORS restricted to https://woyken.github.io."
export CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID
pnpm exec wrangler whoami
if ! confirm "Deploy the production Worker now?"; then warn "Deployment cancelled"; exit 1; fi
pnpm deploy:worker

stage "Publish and verify endpoint"
step "Copy Wrangler's complete Worker URL: https://find-me-home-operations.<your-subdomain>.workers.dev"
ask VITE_WORKER_URL "Paste the production Worker endpoint:"
if [[ "$VITE_WORKER_URL" != "https://find-me-home-operations.karolis-uzkuraitis.workers.dev" ]]; then
  warn "Expected https://find-me-home-operations.karolis-uzkuraitis.workers.dev"
  exit 1
fi
write_env VITE_WORKER_URL "$VITE_WORKER_URL"
set_secret VITE_WORKER_URL "$VITE_WORKER_URL"
pnpm smoke:worker "$VITE_WORKER_URL" "https://woyken.github.io"
open_url "https://github.com/Woyken/find-me-home/actions/workflows/parcel-pages.yml"
say "The next Pages release will deploy and verify this Worker before publishing and smoke-testing the app at https://woyken.github.io/find-me-home/."

finish
