/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CapturePrototypeRouteImport } from './routes/capture-prototype'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAruodasImportRouteImport } from './routes/api/aruodas-import'

const CapturePrototypeRoute = CapturePrototypeRouteImport.update({
  id: '/capture-prototype',
  path: '/capture-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAruodasImportRoute = ApiAruodasImportRouteImport.update({
  id: '/api/aruodas-import',
  path: '/api/aruodas-import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture-prototype': typeof CapturePrototypeRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture-prototype': typeof CapturePrototypeRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture-prototype': typeof CapturePrototypeRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capture-prototype' | '/api/aruodas-import'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capture-prototype' | '/api/aruodas-import'
  id: '__root__' | '/' | '/capture-prototype' | '/api/aruodas-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapturePrototypeRoute: typeof CapturePrototypeRoute
  ApiAruodasImportRoute: typeof ApiAruodasImportRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/capture-prototype': {
      id: '/capture-prototype'
      path: '/capture-prototype'
      fullPath: '/capture-prototype'
      preLoaderRoute: typeof CapturePrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aruodas-import': {
      id: '/api/aruodas-import'
      path: '/api/aruodas-import'
      fullPath: '/api/aruodas-import'
      preLoaderRoute: typeof ApiAruodasImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapturePrototypeRoute: CapturePrototypeRoute,
  ApiAruodasImportRoute: ApiAruodasImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
