/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitPlanRouteImport } from './routes/visit-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceListingsSourceListingIdRouteImport } from './routes/source-listings.$sourceListingId'
import { Route as ImportsTokenRouteImport } from './routes/imports.$token'
import { Route as ApiAruodasImportRouteImport } from './routes/api/aruodas-import'
import { Route as ApiAruodasBookmarkletDotjsRouteImport } from './routes/api/aruodas-bookmarklet[.]js'

const VisitPlanRoute = VisitPlanRouteImport.update({
  id: '/visit-plan',
  path: '/visit-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceListingsSourceListingIdRoute =
  SourceListingsSourceListingIdRouteImport.update({
    id: '/source-listings/$sourceListingId',
    path: '/source-listings/$sourceListingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportsTokenRoute = ImportsTokenRouteImport.update({
  id: '/imports/$token',
  path: '/imports/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAruodasImportRoute = ApiAruodasImportRouteImport.update({
  id: '/api/aruodas-import',
  path: '/api/aruodas-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAruodasBookmarkletDotjsRoute =
  ApiAruodasBookmarkletDotjsRouteImport.update({
    id: '/api/aruodas-bookmarklet.js',
    path: '/api/aruodas-bookmarklet.js',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/visit-plan': typeof VisitPlanRoute
  '/api/aruodas-bookmarklet.js': typeof ApiAruodasBookmarkletDotjsRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
  '/imports/$token': typeof ImportsTokenRoute
  '/source-listings/$sourceListingId': typeof SourceListingsSourceListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/visit-plan': typeof VisitPlanRoute
  '/api/aruodas-bookmarklet.js': typeof ApiAruodasBookmarkletDotjsRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
  '/imports/$token': typeof ImportsTokenRoute
  '/source-listings/$sourceListingId': typeof SourceListingsSourceListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/visit-plan': typeof VisitPlanRoute
  '/api/aruodas-bookmarklet.js': typeof ApiAruodasBookmarkletDotjsRoute
  '/api/aruodas-import': typeof ApiAruodasImportRoute
  '/imports/$token': typeof ImportsTokenRoute
  '/source-listings/$sourceListingId': typeof SourceListingsSourceListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/visit-plan'
    | '/api/aruodas-bookmarklet.js'
    | '/api/aruodas-import'
    | '/imports/$token'
    | '/source-listings/$sourceListingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/visit-plan'
    | '/api/aruodas-bookmarklet.js'
    | '/api/aruodas-import'
    | '/imports/$token'
    | '/source-listings/$sourceListingId'
  id:
    | '__root__'
    | '/'
    | '/visit-plan'
    | '/api/aruodas-bookmarklet.js'
    | '/api/aruodas-import'
    | '/imports/$token'
    | '/source-listings/$sourceListingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VisitPlanRoute: typeof VisitPlanRoute
  ApiAruodasBookmarkletDotjsRoute: typeof ApiAruodasBookmarkletDotjsRoute
  ApiAruodasImportRoute: typeof ApiAruodasImportRoute
  ImportsTokenRoute: typeof ImportsTokenRoute
  SourceListingsSourceListingIdRoute: typeof SourceListingsSourceListingIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/visit-plan': {
      id: '/visit-plan'
      path: '/visit-plan'
      fullPath: '/visit-plan'
      preLoaderRoute: typeof VisitPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-listings/$sourceListingId': {
      id: '/source-listings/$sourceListingId'
      path: '/source-listings/$sourceListingId'
      fullPath: '/source-listings/$sourceListingId'
      preLoaderRoute: typeof SourceListingsSourceListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/$token': {
      id: '/imports/$token'
      path: '/imports/$token'
      fullPath: '/imports/$token'
      preLoaderRoute: typeof ImportsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aruodas-import': {
      id: '/api/aruodas-import'
      path: '/api/aruodas-import'
      fullPath: '/api/aruodas-import'
      preLoaderRoute: typeof ApiAruodasImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aruodas-bookmarklet.js': {
      id: '/api/aruodas-bookmarklet.js'
      path: '/api/aruodas-bookmarklet.js'
      fullPath: '/api/aruodas-bookmarklet.js'
      preLoaderRoute: typeof ApiAruodasBookmarkletDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VisitPlanRoute: VisitPlanRoute,
  ApiAruodasBookmarkletDotjsRoute: ApiAruodasBookmarkletDotjsRoute,
  ApiAruodasImportRoute: ApiAruodasImportRoute,
  ImportsTokenRoute: ImportsTokenRoute,
  SourceListingsSourceListingIdRoute: SourceListingsSourceListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
